import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import Hero2 from "@/components/Hero2";
import Footer from "@/components/Footer/Footer";
import Feature from "@/components/Feature";
import Panel from "@/components/Panel";
import Panel2 from "@/components/Panel2";
import Ghost2 from "../public/assets/SAAVE.png";
import SwordShield from "@/public/assets/swordshield.png";
import Ghost1 from "@/public/assets/aaveLend.png";
import Newsletter from "@/components/Cards/Newsletter";
import Glow1 from "@/public/assets/glow1.png";
import Glow2 from "@/public/assets/glow2.png";
import Glow3 from "@/public/assets/glow3.png";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>HyperFi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero2 />
        <Feature />
        <Panel2
          img={Ghost2}
          glowimg={Glow2}
          title={"Unsure how HyperFi works?"}
          desc={
            "HyperFi simplifies DeFi by providing easy user onboarding, asset management, liquidity provision, staking, governance, analytics, education, and security features. With HyperFi, users can access DeFi services seamlessly and securely, empowering them to participate in the decentralized financial ecosystem."
          }
          link={"/curve"}
        />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
}
